### ISSUE TITLE
ROS teleop app to control custom robots?

### ISSUE THREAD

**Issue by pohetsn** [rosjava/android_apps#44]
Hi, I'm wondering whether ROS teleop can be used to control custom robots, instead of just the turtlebot?   Because when I ran the app, I got the following error message: 

```
03-20 09:11:42.048: E/AndroidRuntime(20661): Process: com.github.rosjava.android_apps.teleop, PID: 20661
03-20 09:11:42.048: E/AndroidRuntime(20661): org.ros.exception.RosRuntimeException: org.ros.exception.ServiceNotFoundException: No such service /turtlebot/start_app of type rocon_app_manager_msgs/StartApp
03-20 09:11:42.048: E/AndroidRuntime(20661):    at com.github.rosjava.android_apps.application_management.AppManager.startApp(AppManager.java:138)
03-20 09:11:42.048: E/AndroidRuntime(20661):    at com.github.rosjava.android_apps.application_management.AppManager.onStart(AppManager.java:202)
03-20 09:11:42.048: E/AndroidRuntime(20661):    at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:506)
03-20 09:11:42.048: E/AndroidRuntime(20661):    at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:503)
03-20 09:11:42.048: E/AndroidRuntime(20661):    at org.ros.concurrent.EventDispatcher.loop(EventDispatcher.java:43)
03-20 09:11:42.048: E/AndroidRuntime(20661):    at org.ros.concurrent.CancellableLoop.run(CancellableLoop.java:56)
03-20 09:11:42.048: E/AndroidRuntime(20661): Caused by: org.ros.exception.ServiceNotFoundException: No such service /turtlebot/start_app of type rocon_app_manager_msgs/StartApp
03-20 09:11:42.048: E/AndroidRuntime(20661):    at org.ros.internal.node.DefaultNode.newServiceClient(DefaultNode.java:356)
03-20 09:11:42.048: E/AndroidRuntime(20661):    at org.ros.internal.node.DefaultNode.newServiceClient(DefaultNode.java:372)
03-20 09:11:42.048: E/AndroidRuntime(20661):    at com.github.rosjava.android_apps.application_management.AppManager.startApp(AppManager.java:134)
03-20 09:11:42.048: E/ActivityManager(643): App crashed! Process: com.github.rosjava.android_apps.teleop
```

It seems that it's looking for a turtlebot specific service /turtlebot/start_app.  I'm wondering whether such dependency is needed.  Thanks

**Comment by stonier** [comment]
You are using hydro versions right?

**Comment by pohetsn** [comment]
The app is hydro, but the ros master is running indigo. Maybe that's the
reason? However, even though the version is different, is it required to have turtlebot service?

**Comment by stonier** [comment]
Indigo went through some upgrades and has moved as much of the android app-robot interaction machinery to the robot side. The android apps and (important for you) their remaps can be configured by setting a yaml for the interactions node on the robot side. So yes, indigo should be able to do what you wish.

I have a colleague looking at fixing one last problem with the visualisation view, once he's done it should be good to go. I'll notify you here when he's done.

**Comment by pohetsn** [comment]
Appreciated!
