### ISSUE TITLE
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.  Please help

### ISSUE THREAD

**Issue by WestbrookZero** [rosjava/android_apps#85]
In the make a map mudule，apk run crash，Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7390)
        at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:3481)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:848)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:848)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:848)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:848)
        at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:848)
        at android.view.View.setFlags(View.java:13273)
        at android.view.View.setClickable(View.java:9837)
        at android.view.View.setOnClickListener(View.java:6117)
        at com.github.rosjava.android_apps.make_a_map.ViewControlLayer.<init>(ViewControlLayer.java:84)
        at com.github.rosjava.android_apps.make_a_map.MainActivity.init(MainActivity.java:300)
        at org.ros.android.RosActivity$1$1.doInBackground(RosActivity.java:89)
        at org.ros.android.RosActivity$1$1.doInBackground(RosActivity.java:86)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by jubeira** [comment]
Hi @WestbrookZero, could you add more info about what you were doing exactly when the exception happened?

**Comment by WestbrookZero** [comment]
I have solved the problem, 
this.act.runOnUiThread(new Runnable() {
            @Override
            public void run() {
                // refresh ui
                ViewControlLayer.this.cameraView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v){
                        swapViews();
                    }
                });
                ViewControlLayer.this.mapView.setClickable(true);
                ViewControlLayer.this.cameraView.setClickable(false);
            }
        });
otherwise the make a map app crash when it started，in the ViewControlLayer.java this line:"this.cameraView.setOnClickListener"

**Comment by jubeira** [comment]
Alright, great! Please feel free to open a PR with your proposed patch if you want.
Thanks in advance!

**Comment by WestbrookZero** [comment]
cannot display map,how to display the map in the make a map app ? 
![image](https://user-images.githubusercontent.com/13358789/55934294-b5504d80-5c62-11e9-82c2-3722f39f9351.png)
